### ISSUE TITLE
Won't build for ios (Cordova 6.0.0)

### ISSUE THREAD

**Issue by av01d** [appfeel/admob-google-cordova#36]
I'm using Cordova 6.0.0. After adding this plugin (cordova plugin add admob-ads), I can't build for ios anymore (cordova build ios). Here's the error message:

```
/Users/arjan/Development/cordova/App.dev/platforms/ios/App/Plugins/admob-ads/CDVAdMobAds.m:101:34: error: 
      no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVAdMobAds *)[super initWithWebView:theWebView];
                           ~~~~~ ^~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

```
Any idea what I can do to make it work?

**Comment by av01d** [comment]
Tested with Cordova 5.4.0, same problem.

**Comment by erbud** [comment]
Same problem.

**Comment by dannygunawan** [comment]
+1

**Comment by appfeel** [comment]
Yep, updated right now it should work with version 4.2.9. Please reopen if fails.

**Comment by av01d** [comment]
It's fixed indeed, builds fine now on iOS.
